pull_request_rules:
  - name: Automatic queue
    conditions:
      - label=ready-to-merge
    actions:
      queue:
queue_rules:
  - name: Bacasable
    queue_conditions:
      - and:
          - label = queue
