merge_queue:
  mode: parallel
  max_parallel_checks: 30
queue_rules:
  - name: standard
    autoqueue: true
    queue_conditions:
      - base=main
      - check-success=ci-gate
    merge_conditions:
      - check-success=ci-gate
    batch_max_wait_time: 30 seconds
    batch_size: 2
defaults:
  actions:
    rebase:
      autosquash: true
      bot_account: sileht
scopes:
  source:
    files:
      docker:
        include:
          - Dockerfile
      backend:
        include:
          - main*.py
      frontend:
        include:
          - frontend/**
      docs:
        include:
          - docs/**
      infra:
        include:
          - infra/**
      api:
        include:
          - api/**
