pull_request_rules:
  - name: Automatic queue
    conditions: 
      - label = autoqueue
    actions:
      queue:
  - name: Testing label
    conditions:
      - label = test
    actions:
      label:
        add:
          - x-commit/init/container

merge_protections:
  - name: Only merge with validation label
    description: Make sure PR has a validation label
    if:
      - base = main
      - label = autoqueue
    success_conditions:
      - label = autoqueue
queue_rules:
  - name: Default
    merge_conditions:
      - and:
          - label = mergeit
          - schedule = 15:00-19:00[America/Vancouver]
 
