merge_queue:
  max_parallel_checks: 1
queue_rules:
  - name: standard
    autoqueue: true
    queue_conditions:
      - base=main
    merge_conditions:
      - check-success=failure
    batch_max_wait_time: 60 seconds
    batch_size: 1
scopes:
  source:
    files:
      python-api:
        include:
          - api/**/*.py
          - libs/shared/**/*.py
      frontend:
        include:
          - web/**/*.js
          - web/**/*.jsx
          - web/**/*.ts
          - web/**/*.tsx
      docs:
        include:
          - docs/**/*.md
          - docs/**/*.mdx
