merge_queue:
  max_parallel_checks: 3
queue_rules:
  - name: standard
    queue_conditions:
      - base=main
      - label=queue
    merge_conditions:
      - check-success=ci-gate
    batch_max_wait_time: 60 seconds
    batch_size: 3
scopes:
  source:
    manual:
