merge_queue:
  max_parallel_checks: 2

queue_rules:
  - name: standard
    autoqueue: true
    queue_conditions:
      - base=main
      - check-success=ci-gate
    batch_max_wait_time: 20 seconds
    batch_size: 2
 
scopes:
  source:
    files:
      docker:
        include:
          - Dockerfile
      docker:
        include:
          - main.py
   

