pull_request_rules:
  - name: Automatic queue
    conditions:
      - label=ready-to-merge
    actions:
      queue:
queue_rules:
  - name: Bacasable
    queue_conditions:
      - and:
          - label = queue
    merge_conditions:
      - and:
          - check-success = continuous-integration/travis-ci
merge_protections:
  - name: Only merge with validation label
    description: Make sure PR has a validation label
    if:
      - base = main
    success_conditions:
      - label = queue
