merge_queue:
  max_parallel_checks: 2
queue_rules:
  - name: standard
    autoqueue: true
    queue_conditions:
      - base=main
      - check-success=ci-gate
      - label=queue
    merge_conditions:
      - check-success=never
    batch_max_wait_time: 60 seconds
    batch_size: 2
scopes:
  source:
    files:
      docker:
        include:
          - Dockerfile
      python:
        include:
          - main*.py
merge_protections:
  - name: Enforce conventional commit
    description: Make sure that we follow https://www.conventionalcommits.org/en/v1.0.0/
    if:
      - base = main
    success_conditions:
      - "title ~=
        ^(fix|feat|docs|style|refactor|perf|test|build|ci|chore|revert)(?:\\(.+\
        \\))?:"
