pull_request_rules:
  - name: Automatic queue
    conditions: []
    actions:
      queue:
merge_protections:
  - name: Only merge with validation label
    description: Make sure PR has a validation label
    if:
      - base = main
    success_conditions:
      - label=autoqueue
