apiVersion: v1
kind: Service
metadata:
  name: bacasable
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: bacasable
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
