name: Mergify Stack Autorebase
on:
  issue_comment:                                     
    types: [created, edited, deleted]

  
jobs:
  autorebase:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/stack-rebase')
    # name: foobar_name
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.issue.pull_request.base.ref }}

      - name: Setup Python 🔧
        uses: actions/setup-python@v5.1.1
        with:
          python-version: 3.12.4

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: mergify-cli
        env:
          TMP: ${{ runner.temp }}
          GITHUB_TOKEN: ${{ secrets.AUTOREBASE_PAT }}
        run: |
          # TODO: changess github.event.changes.base first
          python -m venv "$TMP/venv"
          source "$TMP/venv/bin/activate"
          python -m pip install ./mergify_cli-0.0.0-py3-none-any.whl

          #git config --global user.email "$AUTHOR@users.noreply.github.com"
          #git config --global user.name "$AUTHOR"
          #git branch --set-upstream-to "origin/$BASE"

          mergify --debug stack github-action-auto-rebase
