name: Mergify Stack Autorebase
on:
  pull_request:
    types:
      - edited
  
jobs:
  autorebase:
    # name: foobar_name
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.base.ref }}


      - name: Setup Python 🔧
        uses: actions/setup-python@v5.1.1
        with:
          python-version: 3.12.4

      - name: mergify-cli
        env:
          TMP: ${{ runner.temp }}
          AUTHOR: ${{ github.event.pull_request.user.login }}
          BASE: ${{ github.event.pull_request.base.ref }}
          HEAD: ${{ github.event.pull_request.head.ref }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # TODO: changess github.event.changes.base first
          python -m venv "$TMP/venv"
          source "$TMP/venv/bin/activate"
          python -m pip install ./mergify_cli-0.0.0-py3-none-any.whl

          STACK_BRANCH="${HEAD%%/I*}"
          git config --global user.email "$AUTHOR@users.noreply.github.com"
          git config --global user.name "$AUTHOR"
          git remote -v
          git branch --set-upstream-to "origin/$BASE"

          git branch
          git log --graph --abbrev-commit --pretty="tformat:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%an %cr)%Creset" -15

          mergify --debug stack checkout --author "$AUTHOR" --repo "$GITHUB_REPOSITORY" --branch "$STACK_BRANCH" --branch-prefix "" --trunk "origin/$BASE"

          git branch
          git log --graph --abbrev-commit --pretty="tformat:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%an %cr)%Creset" -15

          mergify --debug stack push --author "$AUTHOR" --branch "$STACK_BRANCH" --branch-prefix "" --trunk "origin/$BASE"




