name: CI

on:
  pull_request:

jobs:
  failure:
    runs-on: ubuntu-latest
    steps:
      - name: Failure
        run: |
          echo boom
          exit 1

  changes:
    runs-on: ubuntu-latest
    outputs:
      base: ${{ steps.git-refs.outputs.base }}
      head: ${{ steps.git-refs.outputs.head }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: Mergifyio/gha-mergify-ci@v15
        id: git-refs
        with:
          action: scopes-git-refs
      - name: Detect affected scopes
        id: detect
        env:
          BASE: ${{ steps.git-refs.outputs.base }}
          HEAD: ${{ steps.git-refs.outputs.head }}
        run: |
          # mimic nx project
          echo "scopes=testing,foobar" >> "$GITHUB_OUTPUT"
      - uses: Mergifyio/gha-mergify-ci@v15
        with:
          action: scopes-upload
          scopes: ${{ steps.detect.outputs.scopes }}
          token: ${{ secrets.MERGIFY_TOKEN }}

  ci-gate:
    if: ${{ !cancelled() }}
    needs:
      - changes
    runs-on: ubuntu-latest
    steps:
      - name: Verify all jobs succeeded
        uses: Mergifyio/gha-mergify-ci@v15
        with:
          action: wait-jobs
          jobs: ${{ toJSON(needs) }}
      
